apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql
  name: mysql
spec:

  type: ClusterIP

  ports:
  - name: "3306"
    #port is the port exposed to the other pods
    #targetPort is the port exposed by the container
    port: 3306
    targetPort: 3306
  selector:
    app: mysql
